title: Wanying Xu
email: xww@case.edu
description: >-
  I'm a Ph.D. candidate in CASE WESTERN RESERVE UNIVSERITY.
baseurl: ""
url: "https://wanyingx.github.io/wy-xu.github.io/"
twitter_username: Wanying Xu
github_username: Wanying Xu

theme: minima

# Build settings
markdown: kramdown
